# render.yml

services:
  - type: web
    name: planit-client
    env: static
    branch: main

    buildCommand: npm install && npm run build

    staticPublishPath: ./dist

    routes:
      - type: rewrite
        source: /*
        destination: /index.html
